url: "https://comunidadruby.mx"

permalink: pretty

email: "info@comunidadruby.mx"

available_locales: [en, es]
default_locale: es
prefix_default_locale: false

upcoming_event: true

event:
  event_path: "octubre_2024"
  current_announcement_path: "anuncio_final.png"
  venue:
    address: "Manuel Lopez Cotilla 1599"
    google_map_link: "https://maps.app.goo.gl/8eJGJF3eR4ryZ19H8"
  links:
    eventbrite: "https://www.eventbrite.com.mx/e/comunidad-ruby-mx-sesion-octubre-2024-tickets-1039586600507"
    youtube: "https://www.youtube.com/watch?v=QMuQ5e5qI3A"

  es:
    date: "30 de octubre del 2024"
    venue: "Envato Guadalajara"
  en:
    date: "October 30th 2024"
    venue: "Envato Guadalajara"

collections:
  eventos:
    output: true
    permalink: simple
    future: true

  events:
    output: true
    permalink: /en/:collection/:slug.*
    future: true

