url: "https://comunidadruby.mx"

permalink: pretty

email: "info@comunidadruby.mx"

available_locales: [en, es]
default_locale: es
prefix_default_locale: false

upcoming_event: yes

event:
  event_path: "enero_2025"
  current_announcement_path: "tercer_anuncio.png"
  venue:
    address: "Paseo de los Virreyes 45, Puera de Hierro"
    google_map_link: "https://maps.app.goo.gl/X5mkA5XDSPY9kUc89"
  links:
    eventbrite: "https://www.eventbrite.com.mx/e/comunidad-ruby-mx-sesion-enero-2025-tickets-1142947941059?aff=oddtdtcreator"
    youtube: "https://www.youtube.com/watch?v=16gi5GHoJI4"

  es:
    date: "30 de enero del 2025"
    venue: "BBVA Spark Space Guadalajara"
  en:
    date: "January 30th 2025"
    venue: "BBVA Spark Space Guadalajara"

collections:
  eventos:
    output: true
    permalink: simple
    future: true

  events:
    output: true
    permalink: /en/:collection/:slug.*
    future: true

