url: "https://comunidadruby.mx"

permalink: pretty

email: "info@comunidadruby.mx"

available_locales: [en, es]
default_locale: es
prefix_default_locale: false

upcoming_event: true

collections:
  eventos:
    output: true
    permalink: simple
    future: true

  events:
    output: true
    permalink: /en/:collection/:slug.*
    future: true

