url: "https://comunidadruby.mx"

permalink: pretty

email: "info@comunidadruby.mx"

available_locales: [en, es]
default_locale: es
prefix_default_locale: false

upcoming_event: yes

event:
  event_path: "junio_2025"
  current_announcement_path: "primer_anuncio.png"
  sponsor_name: "Wizeline"
  venue:
    address: "Amado Nervo 2200, Jardines del Sol, Zapopan, Jalisco"
    google_map_link: https://maps.app.goo.gl/NauLFkywQDjRDuW1A"
  links:
    eventbrite: "https://www.eventbrite.com.mx/e/comunidad-ruby-mx-sesion-junio-2025-tickets-1406613090619?aff=oddtdtcreator"
    youtube: "https://www.youtube.com/watch?v=9aSe6_WlxCo"
    sponsor: "https://www.wizeline.com"

  es:
    date: "26 de Junio del 2025"
    venue: "Wizeline"
  en:
    date: "June 26th 2025"
    venue: "Wizeline"

collections:
  eventos:
    output: true
    permalink: simple
    future: true

  events:
    output: true
    permalink: /en/:collection/:slug.*
    future: true

