url: "https://comunidadruby.mx"

permalink: pretty

email: "info@comunidadruby.mx"

available_locales: [en, es]
default_locale: es
prefix_default_locale: false

upcoming_event: false

event:
  event_path: "mayo_2024"
  current_announcement_path: "segundo_anuncio.jpg"
  venue:
    address: "Acueducto 6050 - Plaza Acueducto"
    google_map_link: "https://maps.app.goo.gl/cNpyQVmvsEs3JGvN7"
  links:
    eventbrite: "https://www.eventbrite.com.mx/e/ruby-mx-playasontech-sesion-especial-tickets-888435433297"
    youtube: "https://www.youtube.com/watch?v=QMuQ5e5qI3A"

  es:
    date: "16 de mayo del 2024"
    venue: "Density Labs Guadalajara"
  en:
    date: "May 16th 2024"
    venue: "Density Labs Guadalajara"

collections:
  eventos:
    output: true
    permalink: simple
    future: true

  events:
    output: true
    permalink: /en/:collection/:slug.*
    future: true

